Repository VB10/sesimiduy, pull requests merged in 2023-02, with the labels that each got.

#2 Added rivepod, state and other thinks
  analysis_options.yaml
  assets/translations/tr-TR.json
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/core/enums/core_localize.dart
  lib/features/home/view/home_view.dart
  lib/features/home/view_model/home_view_model.dart
  lib/main.dart
  lib/product/app_builder.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: good first issue

#14 Error & Success dialogs completed for register.
  assets/translations/tr-TR.json
  ios/Podfile.lock
  lib/features/home/view/home_view.dart
  lib/product/init/language/locale_keys.g.dart
  lib/product/utility/decorations/empty_box.dart
  lib/product/utility/dialog/display_dialog_mixin.dart
  lib/product/utility/dialog/register_error_dialog.dart
  lib/product/utility/dialog/register_success_dialog.dart
Labels: enhancement

#58 fixed general requiretmenss #45
  assets/translations/tr-TR.json
  lib/features/login/view/login_view.dart
  lib/features/login/view/widget/complete_buutton.dart
  lib/features/login/view/widget/current_map_button.dart
  lib/features/login/view/widget/going_help_button.dart
  lib/features/login/view/widget/help_wanted_button.dart
  lib/features/login/view/widget/index.dart
  lib/main.dart
  lib/product/items/colors_custom.dart
  lib/product/utility/decorations/style/button_rectangle_border.dart
  lib/product/utility/mixin/loading_state_mixin.dart
  lib/product/widget/text/button_large_text.dart
  lib/product/widget/text/index.dart
Labels: bug
